steps:
  # Create the .env file
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "NEXT_PUBLIC_CIVITAS_API_URL=${_NEXT_PUBLIC_CIVITAS_API_URL}" > .env.production && \
        echo "NEXT_PUBLIC_GW_API_URL=${_NEXT_PUBLIC_GW_API_URL}" > .env.production && \
        echo "MAPBOX_ACCESS_TOKEN=${_MAPBOX_ACCESS_TOKEN}" >> .env.production && \
        echo "NEXT_PUBLIC_VISION_AI_URL=http://staging.app.dados.rio/vision-ai" >> .env.production
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA"]
  # Kustomize: set the image in the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    entrypoint: "kustomize"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/project-id/civitas=gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA"
  # Kustomize: apply the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    entrypoint: "kustomize"
    args: ["build", ".", "-o", "staging.yaml"]
  # Deploy the application to the GKE cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    args:
      - "run"
      - "--filename=staging.yaml"
      - "--location=us-central1"
      - "--cluster=datario"
      - "--project=datario"

images:
  - "gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA"
