steps:
  # Install dependencies (with optimizations)
  - name: "node:20-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        corepack enable && \
        corepack prepare pnpm@9.15.2 --activate && \
        pnpm install --frozen-lockfile --prefer-offline
    id: "install-deps"

  # Run only critical tests in parallel
  - name: "node:20-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        corepack enable && \
        corepack prepare pnpm@9.15.2 --activate && \
        pnpm test -- --passWithNoTests --watchAll=false --coverage=false --testPathPatterns="(critical|integration|radar.*bug)" --maxWorkers=2
    waitFor: ["install-deps"]
    id: "run-tests"

  # Create the .env file (can run in parallel with tests)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "NEXT_PUBLIC_CIVITAS_API_URL=https://staging.api.civitas.rio" > .env.production && \
        echo "NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiZXNjcml0b3Jpb2RlZGFkb3MiLCJhIjoiY2t3bWdmcHpjMmJ2cTJucWJ4MGQ1Mm1kbiJ9.4hHJX-1pSevYoBbja7Pq4w" >> .env.production && \
        echo "NEXT_PUBLIC_VISION_AI_URL=http://staging.app.dados.rio/vision-ai" >> .env.production
    waitFor: ["-"]
    id: "create-env"

  # Build the container image with cache optimization
  - name: "gcr.io/cloud-builders/docker"
    args: 
      - "build"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/civitas:staging-latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/civitas:staging-latest"
      - "."
    waitFor: ["run-tests", "create-env"]
  # Push both images to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/civitas:staging-latest"]
  # Kustomize: set the image in the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    entrypoint: "kustomize"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/project-id/civitas=gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA"
  # Kustomize: apply the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    entrypoint: "kustomize"
    args: ["build", ".", "-o", "staging.yaml"]
  # Deploy the application to the GKE cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/staging"
    args:
      - "run"
      - "--filename=staging.yaml"
      - "--location=us-central1"
      - "--cluster=datario"
      - "--project=datario"

images:
  - "gcr.io/$PROJECT_ID/civitas:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/civitas:staging-latest"

