// Importar extensões de Date para garantir que sejam carregadas
import './date-extensions'
import './string-extensions'

// Re-exportar funções utilitárias
export * from './date-extensions'
export * from './calculate-color-gradient'
export * from './csv'
export * from './download-file'
export * from './error-handlers'
export * from './format-car-path-response'
export * from './format-reports-request'
export * from './formatLocation'
export * from './getBoundingBox'
export * from './haversine-distance'
export * from './is-cloned'
export * from './logout'
export * from './rio-viewport'
export * from './set-all-values'
export * from './string-formatters'
export * from './template-messages'
export * from './to-query-params'
export * from './validate-cnpj'
export * from './validate-cpf'
export * from './zod-schemas'
