name: Auto approve PRs for core maintainers

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'gabriel-milan' || github.actor == 'victorassiso'
    steps:
      - uses: hmarr/auto-approve-action@v3