name: Deployment - Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        env:
          CI: false
          REACT_APP_CIVITAS_API_URL: https://api.civitas.rio/
        run: |
          npm run build

      - name: Create CNAME file
        run: |
          echo "app.civitas.rio" > build/CNAME

      - name: Push to gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build add --all
          git commit -m "Deploy"
          git push origin HEAD:gh-pages --force